version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3002:3001"  # Changed from 3001 to avoid conflict
    environment:
      - NODE_ENV=production
      - DOCUSEAL_API_KEY=${DOCUSEAL_API_KEY}
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge